### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by rkinlen** [AppIeWorm/deCard#2]
Hi there, please could you update this to arm64e? Or moderne jailbreaks.

**Comment by MatoiDev** [comment]
Hi! 
[here you go](https://github.com/MatoiDev/deCard/releases/tag/deCardv2.2.0Rootless)

**Comment by rkinlen** [comment]
Thanks, do you have any other images available?

**Comment by MatoiDev** [comment]
Unfortunately, I don't :( But it's easy to make your own design in photoshop ([here is a .png pattern)](https://github.com/MatoiDev/deCard/blob/main/decard/Cards.bundle/customCardPattern.png) or you can download this [amazing cards set](https://repo.twickd.com/get/com.twickd.dylan-west.mycards)
